version: 1.0
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:2022.03"
  steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run: 
        name: "test pipeline"
        command: echo "hello folks"  